export { default as Dashboard } from "./dashboard/Dashboard";
export { default as Assignment } from "./assignment/Assignment";
export { default as AssignmentMark } from "./assignmentMark/AssignmentMark";
export { default as Quiz } from "./quiz/Quiz";
export { default as Videos } from "./videos/Videos";
export { default as AdminNavbar } from "./dashboard/AdminNavbar";
export { default as Video } from "./videos/Video";
export { default as AddVideo } from "./videos/AddVideo";
export { default as EditVideo } from "./videos/EditVideo";
